### PR TITLE
Validate model files

### LINKED ISSUE #27: Add validation checks for custom model files
Continues work from #25. Will add checks to enforce the correct naming patterns (file names and internal function names), will also check for duplicates, and will throw helpful warnings/error messages to the user if any check fails.

Relevant comment from #25:
              > For now, I've just added documentation that explains how the files should be formatted. I think the current method is fine, but I think we should add additional validation steps to ensure there are no duplicate file/model names and to give helpful warning messages to the user if they incorrectly format their models.

Will make the validation checks in a new branch.

_Originally posted by @apulsipher in https://github.com/UofUEpiBio/epiworldRShiny/issues/25#issuecomment-2766626570_

### PR DESCRIPTION
**Pull request by apulsipher**
Add validation for model files, especially custom models:

- Ensure models follow the correct format
- Check for duplicates

Branched from the `measlesquarantine` to bring in latest from George's work.

### CODE REVIEW

**Comment by apulsipher** [comment]
@gvegayon This is ready for review. I've set it to merge into your measles branch, since you are still working on that and the check failures appear to be due to the measles branch things you're working on. The README file changes are what I pulled in from main, not something I added while working on this here.

Let me know what you think!

**Comment by gvegayon** [comment]
Great! The CI is failing b/c of something about bslib (probably my fault). Can you fix that on the fly with this PR? Thanks!

**Comment by apulsipher** [comment]
@gvegayon I fixed the failing check. Part of the issue was missing bslib in the Imports and the other issue was a failing example (`spinner()` in `functions-ui.R`). I simply wrapped the spinner example in a `\dontrun{}` block, because I wasn't sure what sort of UI element to pass in as the `what` param. Let me know if you want any other changes before merging this!

File: R/functions-ui.R [hunk 1]
```diff
@@ -269,6 +269,114 @@ seed_input <- function(model_name) {
     )
 }
 
+# Helper function to validate a given model file
+#' @rdname epiworldrshiny-ui
+#' @param model_filename The name of the model file to be validated.
+#' @return
```
Comment (gvegayon) [inline R/functions-ui.R:275]: To keep the roxygen tags but avoid creating a manual, this is what you do.

```suggestion
#' @noRd
#' @return
```

File: R/functions-ui.R [hunk 2]
```diff
@@ -269,6 +269,114 @@ seed_input <- function(model_name) {
...
+#'   with duplicates removed.
+remove_duplicates <- function(custom_models, system_models) {
+  # Remove duplicates from custom models
+  custom_models <- custom_models[
+    !basename(custom_models) %in% basename(system_models)
+  ]
+
+  # Print warning if any duplicates were found
+  if (length(custom_models) < length(system_models)) {
+    message("Custom model path contains duplicated system models.
```
Comment (gvegayon) [inline R/functions-ui.R]: Add info about what was the removed duplicate.

File: R/functions-ui.R [hunk 3]
```diff
@@ -421,7 +531,7 @@ simulate_button <- function(model_name) {
 #' @rdname epiworldrshiny-ui
 #' @param what The UI element to be wrapped in a spinner.
 #' @examples
-#' spinner()
+#' \dontrun{spinner()}
```
Comment (gvegayon) [inline R/functions-ui.R:540]: Let's remove the spinner in a separate issue (there's an R package we import just for this).

**Review by gvegayon — APPROVED** [review]
